# Generated by Django 4.2.6 on 2023-11-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0
            ),
        ),
    ]
